# grafana-values.yaml
# Grafana configuration for ingress controller monitoring

# Admin credentials
adminUser: admin
adminPassword: Caesar426800.

# Service configuration
service:
  type: NodePort
  nodePort: 30030
  port: 80

# Resource allocation
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

# Persistence
persistence:
  enabled: true
  size: 5Gi
  storageClassName: "local-path"

# Datasources (auto-configure Prometheus)
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server:80
      access: proxy
      isDefault: true
      editable: true

# Dashboard providers
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default

# Pre-installed dashboards
dashboards:
  default:
    # Kubernetes cluster overview
    kubernetes-cluster:
      gnetId: 7249
      revision: 1
      datasource: Prometheus
    
    # NGINX Ingress Controller
    nginx-ingress:
      gnetId: 9614
      revision: 1
      datasource: Prometheus
    
    # Traefik Dashboard
    traefik:
      gnetId: 4475
      revision: 5
      datasource: Prometheus
    
    # Node Exporter (system metrics)
    node-exporter:
      gnetId: 1860
      revision: 31
      datasource: Prometheus
    
    # Kubernetes Pod Metrics
    kubernetes-pods:
      gnetId: 6417
      revision: 1
      datasource: Prometheus

# Plugins (optional but useful)
plugins:
  - grafana-clock-panel
  - grafana-simple-json-datasource
  - grafana-worldmap-panel

# Environment variables
env:
  GF_EXPLORE_ENABLED: true
  GF_PANELS_DISABLE_SANITIZE_HTML: true
  GF_LOG_FILTERS: rendering:debug
  GF_SECURITY_ADMIN_PASSWORD: ""

# Security settings
securityContext:
  runAsUser: 472
  runAsGroup: 472
  fsGroup: 472

# Ingress (optional - if you want to access via ingress instead of NodePort)
ingress:
  enabled: false

# SMTP settings (optional - for alerting)
smtp:
  enabled: false

# Enable anonymous access (optional - for easier demo)
grafana.ini:
  auth.anonymous:
    enabled: false
  auth:
    disable_login_form: false
  security:
    admin_user: admin
    # admin_password: Caesar426800.