ingress:
  enabled: true
  className: "apisix"
  annotations:
    kubernetes.io/ingress.class: "apisix"
    apisix.ingress.kubernetes.io/enable-access-log: "true"
    k8s.apisix.apache.org/load-balancer: "least_conn"
    prometheus.io/scrape: "true"
    prometheus.io/port: "9091"
  
  hosts:
    - host: nipa.sudlor.me
      paths:
        - path: /api
          pathType: Prefix
          backend:
            service:
              name: backend
              port:
                number: 8000
        - path: /
          pathType: Prefix
          backend:
            service:
              name: frontend
              port:
                number: 3000
  
  tls: []

# Enable monitoring
monitoring:
  serviceMonitor:
    enabled: true
    metricsPath: /apisix/prometheus/metrics
    metricsPort: apisix-admin
