ingress:
  enabled: true
  className: "nginx"
  annotations:
    # nginx.ingress.kubernetes.io/configuration-snippet: |
    #   more_set_headers "X-Ingress-Controller: nginx";
    #   more_set_headers "X-Request-ID: $request_id";
    # This annotation is crucial for path-based routing to work correctly.
    # nginx.ingress.kubernetes.io/rewrite-target: /$2
    # Enable access logs for monitoring
    # nginx.ingress.kubernetes.io/enable-access-log: "true"
    # Monitoring
    prometheus.io/scrape: "true"
    prometheus.io/port: "9113"
  
  hosts:
    - host: nipa.sudlor.me
      paths:
        # Route requests for http://nipa.sudlor.me/api/... to the backend service
        - path: /api
          pathType: Prefix # Changed from Prefix
          backend:
            service:
              name: backend
              port:
                number: 8000
        # Route all other requests to the frontend service
        - path: /
          pathType: Prefix # Changed from Prefix
          backend:
            service:
              name: frontend
              port:
                number: 3000

  tls: []

monitoring:
  serviceMonitor:
    enabled: true