nameOverride: ""
alertmanager:
  enabled: false
grafana:
  enabled: true
  fullnameOverride: "grafana"
  nodeSelector:
    kubernetes.io/os: linux
  adminPassword: admin  
    # port: 80
  persistence:
    enabled: true
    size: 5Gi
    storageClassName: "local-path"
prometheusOperator:
  fullnameOverride: "prometheus-operator"
  enabled: true
  nodeSelector:
    kubernetes.io/os: linux
kube-state-metrics:
  fullnameOverride: "kube-state-metrics"
  nodeSelector:
    kubernetes.io/os: linux
kubelet:
  serviceMonitor:
    enabled: true
    interval: "15s"
prometheus:
  fullnameOverride: "prometheus"
    # port: 80
  serviceAccount:
    create: true
    name: "prometheus-k8s"
  prometheusSpec:
    nodeSelector:
      kubernetes.io/os: linux
    retention: "30d"  
  persistence:
    enabled: true
    size: 10Gi
    storageClassName: "local-path"
prometheus-node-exporter:
  fullnameOverride: "node-exporter"
  prometheus:
    monitor:
      enabled: true
      interval: "15s"