apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "myapp.fullname" . }}-config
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  # Backend service URL for frontend (if needed)
  # BACKEND_SERVICE_URL: "http://{{ include "myapp.fullname" . }}-backend:{{ .Values.backend.service.port }}"