{{- if and .Values.ingress.enabled .Values.monitoring.serviceMonitor.enabled }}
{{/*
ServiceMonitor for application metrics
*/}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "myapp.fullname" . }}-app-metrics
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
    monitoring: "true"
spec:
  selector:
    matchLabels:
      {{- include "myapp.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: http
    interval: 15s
    path: /metrics
    honorLabels: true
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
{{- end }}