# -- Create a default IngressClass for Traefik
ingressClass:  # @schema additionalProperties: false
  name: "traefik-monitoring"

service:
  type: NodePort


ports:
  web:
    enabled: true
    nodePort: 30030

  websecure:
    enabled: true
    nodePort: 30033
