controller:
  name: haproxy-ingress
  replicaCount: 2
  
  # Resource allocation
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 512Mi

  # Service configuration
  service:
    type: NodePort
    labels:
      ingress-monitor: haproxy
    nodePorts:
      http: 30080
      https: 30443
  metrics:
    enabled: true


  # Enable statistics for Prometheus
  # stat:
  #   enabled: true
  #   port: 9101
  #   # Expose Prometheus metrics endpoint on /metrics
  #   prometheus:
  #     enabled: true
  #     path: /metrics
      

# Default backend (HAProxy requires this)
defaultBackend:
  enabled: true
  replicaCount: 1
  
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

# ServiceMonitor for Prometheus
serviceMonitor:
  enabled: true
  namespace: monitoring
  endpoints:
    - port: stat
      interval: 15s
      path: /metrics