controller:

  config:
    allow-snippet-annotations: "true"
    annotations-risk-level: "Critical"

  # Run two instances of the controller for availability
  replicaCount: 1
  
  # Basic resource allocation
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 512Mi

  # Expose the controller on the nodes for external access
  service:
    enabled: true
    type: NodePort
    nodePorts:
      http: 30080
      https: 30443

  # Enable metrics for Prometheus to scrape
  metrics:
    enabled: true
    service:
      enabled: true
      type: ClusterIP
      port: 10254
      labels:
        ingress-monitor: nginx
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: prometheus
      interval: 15s
      scrapeTimeout: 10s
      # This MUST match the namespace you deploy to
      namespace: nipa-travel
