controller:

  config:
    allow-snippet-annotations: "true"
    annotations-risk-level: "Critical"

  # Run two instances of the controller for availability
  replicaCount: 2
  
  # Basic resource allocation
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 512Mi

  # Expose the controller on the nodes for external access
  service:
    enabled: true
    type: NodePort
    nodePorts:
      http: 30080
      https: 30443

  # Enable metrics for Prometheus to scrape
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      # This MUST match the namespace you deploy to
      namespace: nipa-travel 


# Disable admission webhooks to prevent validation errors during testing.
admissionWebhooks:
  enabled: false